config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :groups
  resources :payments
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :groups, only: [] do
    resources :payments, only: [:new, :create, :destroy]
  end

  # Defines the root path route ("/")
  root "groups#index"
  get 'home' => 'splash#splash', as: :splash
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :manage, :all, user_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :payments, join_table: 'groups_payments'

  validates :name, presence: true, length: { maximum: 50 }
  validates :icon, presence: true, length: { maximum: 100 }

  def transactions_total
    payments.sum(:amount)
  end
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :groups, join_table: 'groups_payments'

  validates :name, presence: true, length: { maximum: 50 }
  validates :amount, presence: true, numericality: { greater_than: 0, alert: 'must be greater than 0' }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :payments
  has_many :groups
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :update_allowed_parameters, if: :devise_controller?

  def redirect_to_splash
    redirect_to splash_path
  end

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :password_confirmation, :current_password)
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :redirect_to_splash, unless: :signed_in?
  load_and_authorize_resource
  before_action :set_group, only: %i[show edit update destroy]

  # GET /groups or /groups.json
  def index
    @groups = Group.where(user_id: current_user.id)
  end

  # GET /groups/1 or /groups/1.json
  def show
    @payments = @group.payments.where(user_id: current_user.id).order(created_at: :desc)
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit; end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_params)
    @group.user = current_user

    respond_to do |format|
      if @group.save
        format.html { redirect_to groups_path, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to group_url(@group), notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:user_id, :name, :icon)
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :redirect_to_splash, unless: :signed_in?
  load_and_authorize_resource
  before_action :set_payment, only: %i[show edit update destroy]

  # GET /payments or /payments.json
  def index
    @payments = Payment.all
  end

  # GET /payments/1 or /payments/1.json
  def show; end

  # GET /payments/new
  def new
    @group = Group.find(params[:group_id])
    @payment = Payment.new
    @groups = Group.where(user_id: current_user.id)
  end

  # GET /payments/1/edit
  def edit; end

  # POST /payments or /payments.json
  def create
    @payment = Payment.new(payment_params)
    @payment.user = current_user
    @group = Group.find(params[:group_id])
    if params[:grp_ids]
      params[:grp_ids].each do |group_id|
        group = Group.find(group_id)
        group.payments << @payment
      end
    else
      redirect_to new_group_payment_path(@group), flash: { alert: 'You must select at least one category.' }
      return
    end

    respond_to do |format|
      if @payment.save
        format.html { redirect_to group_path(@group), notice: 'Payment was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1 or /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to payment_url(@payment), notice: 'Payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1 or /payments/1.json
  def destroy
    @payment.destroy
    @group = Group.find(params[:group_id])

    respond_to do |format|
      format.html { redirect_to group_url(@group), notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_payment
    @payment = Payment.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def payment_params
    params.require(:payment).permit(:name, :amount)
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def splash
    render 'splash/splash'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :redirect_to_splash, unless: :signed_in?
  load_and_authorize_resource
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.fetch(:user, {})
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: group, class: "new_group") do |form| %>
  <% if group.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>
      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :name, hidden: true %><br/>
    <%= form.text_field :name, placeholder: 'Category name', required: true %>
  </div>
  <div>
    <%= form.text_field :icon, placeholder: 'Icon url', value: 'https://picsum.photos/90', required: true %>
  </div>
  <div class="verb">
    <%= form.submit "Create", class: 'btn create' %>
  </div>
<% end %>

app/views/groups/_group.html.erb
<div id="<%= dom_id group %>" class="group">
  <div class="icon">
    <img src="https://picsum.photos/90" alt="randy">
  </div>
  <div class="info">
    <%= group.name %>
  </div>
  <div class="total">
    <%= number_to_currency group.transactions_total %>
  </div>
</div>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render "form", group: @group %>

<br>

<div>
  <%= link_to "Show this group", @group %> |
  <%= link_to "Back to groups", groups_path %>
</div>

app/views/groups/index.html.erb
<%= render partial: "shared/navigation", locals: {icon_type:'fa-solid', icon_name: 'arrow-left', title:'CATEGORIES', right:''} %>
<p style="color: green"><%= notice %></p>
<div id="groups">
  <% if @groups.any? %>
    <% @groups.each do |group| %>
      <%= link_to (group) do %>
        <%= render group %>
      <% end %>
    <% end %>
  <% else %>
    <p class="info">No groups yet.</p>
  <% end %>
</div>
<div class="verb">
  <%= link_to "New Category", new_group_path, class: 'btn create groups' %>
</div>

app/views/groups/new.html.erb
<%= render partial: "shared/navigation", locals: {icon_type:'fa-solid', icon_name: 'arrow-left', title: 'NEW CATEGORY', right:''} %>
<%= render "form", group: @group %>
<br>

app/views/groups/show.html.erb
<%= render partial: "shared/navigation", locals: {icon_type:'fa-solid', icon_name: 'arrow-left', title:"TRANSACTIONS", right:''} %>
<div class="show-actions">
  <%= link_to "Edit", edit_group_path(@group) %>
  <%= button_to "Delete", @group, method: :delete %>
</div>
<%= render @group %>
<div class="verb">
  <%= link_to "New Transaction", new_group_payment_path(@group), class: 'btn create groups' %>
</div>
<div id="payments">
  <% if @payments.any? %>
    <% @payments.each do |payment| %>
      <%= render partial: "payments/payment", locals: {payment: payment, group: @group} %>
    <% end %>
  <% else %>
    <p class="info">No transactions yet.</p>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PayEye</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/payments/_form.html.erb
<%= form_with(model: payment, url: group_payments_path(group), class: "new_payment") do |form| %>
  <% if payment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(payment.errors.count, "error") %> prohibited this payment from being saved:</h2>
      <ul>
        <% payment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :name, hidden: true %> <br/>
    <%= form.text_field :name, placeholder: 'Name', required: true %>
  </div>
  <div>
    <%= form.number_field :amount, placeholder: 'Amount', required: true %>
  </div>
  <div class="selections">
    <%@groups.each do |grp|%>
      <div class="selection">
        <p><%= grp.name %></p>
        <%= check_box_tag "grp_ids[]", grp.id, grp.id == group.id  %>
      </div>
    <%end%>
  </div>
</div>
<div class="verb">
  <%= form.submit "Create", class: 'btn create' %>
</div>
<% end %>

app/views/payments/_payment.html.erb
<div id="<%= dom_id payment %>" class="payment">
  <div class="icon">
    <img src="https://picsum.photos/60" alt="randy">
  </div>
  <div class="info">
    <p><%= payment.name %></p>
    <p class="date"><%=payment.created_at.strftime('%d %b %Y')%></p>
  </div>
  <div class="total">
    <p class="amount"><%= number_to_currency payment.amount %></p>
    <div class="payment-actions">
      <%= button_to icon('fa-solid', 'trash'), group_payment_url(group, payment), method: :delete, class: 'btn delete'%>
    </div>
  </div>
</div>

app/views/payments/edit.html.erb
<h1>Editing payment</h1>

<%= render "form", payment: @payment %>

<br>

<div>
  <%= link_to "Show this payment", @payment %> |
  <%= link_to "Back to payments", payments_path %>
</div>

app/views/payments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Payments</h1>

<div id="payments">
  <% @payments.each do |payment| %>
    <%= render payment %>
    <p>
      <%= link_to "Show this payment", payment %>
    </p>
  <% end %>
</div>

<%= link_to "New payment", new_payment_path %>

app/views/payments/new.html.erb
<%= render partial: "shared/navigation", locals: {icon_type:'fa-solid', icon_name: 'arrow-left', title: 'NEW TRANSACTION', right:''} %>
<%= render partial: "form", locals: {payment: @payment, group: @group} %>

app/views/payments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @payment %>

<div>
  <%= link_to "Edit this payment", edit_payment_path(@payment) %> |
  <%= link_to "Back to payments", payments_path %>

  <%= button_to "Destroy this payment", @payment, method: :delete %>
</div>

app/views/shared/_navigation.html.erb
<nav>
  <div class="icon"><%=link_to icon('fa-solid', 'angle-left'), groups_path, id: 'home'%> </div>
  <div class="title"><%=title%></div>
  <div class="icon"><%=button_to icon('fa-solid', 'arrow-right-from-bracket'), destroy_user_session_path, method: :delete %></div>
</nav>

app/views/splash/splash.html.erb
<div class="splash">
  <div class="logo"><%=image_tag("logo.png", alt: "Spendify App")%></div>
  <div class="actions">
    <%= link_to "LOG IN", new_user_session_path, class: 'btn' %>
    <%= link_to "SIGN UP", new_user_registration_path, class: 'btn secondary' %>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>